//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDiscussion
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int DiscussionId { get; set; }
        public bool IsObserver { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
